spring.data.mongodb.uri=mongodb+srv://subugee:subugee222@cluster0.shfpbhv.mongodb.net/myDatabase?retryWrites=true&w=majority&appName=Cluster0

# Server
server.port=8080

# Camel
camel.springboot.name=CamelMongoApp